apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloudflared.fullname" . }}
  labels:
    app: {{ include "cloudflared.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cloudflared.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "cloudflared.name" . }}
    spec:
      serviceAccountName: {{ include "cloudflared.serviceAccountName" . }}
      containers:
        - name: cloudflared
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - tunnel
            - --config
            - /etc/cloudflared/config.yaml
            - run
          volumeMounts:
            - name: config
              mountPath: /etc/cloudflared
            - name: creds
              mountPath: /etc/cloudflared/creds
              readOnly: true
          resources:
{{ toYaml .Values.resources | indent 12 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "cloudflared.fullname" . }}
        - name: creds
          secret:
            secretName: {{ .Values.cloudflared.credentialsSecret }}

